// src/components/team-data.jsx

const TeamData = [
  {
    id: 1,
    name: "Ali Raza",
    role: "Career Counselor",
    category: "Advisory",
    img: "https://randomuser.me/api/portraits/men/11.jpg",
    bio: "Expert in career guidance and educational counseling for parents and students.",
  },
  {
    id: 2,
    name: "Ayesha Khan",
    role: "English Language Trainer",
    category: "Training",
    img: "https://randomuser.me/api/portraits/women/12.jpg",
    bio: "Certified English trainer with 8 years of experience improving communication skills.",
  },
  {
    id: 3,
    name: "Bilal Ahmed",
    role: "STEM Mentor",
    category: "Mentoring",
    img: "https://randomuser.me/api/portraits/men/13.jpg",
    bio: "Specializes in developing critical thinking and project-based learning in STEM subjects.",
  },
  {
    id: 4,
    name: "Sana Malik",
    role: "Parent Advisor",
    category: "Advisory",
    img: "https://randomuser.me/api/portraits/women/14.jpg",
    bio: "Helps parents understand modern educational strategies and support systems.",
  },
  {
    id: 5,
    name: "Usman Tariq",
    role: "Career Coach",
    category: "Counseling",
    img: "https://randomuser.me/api/portraits/men/15.jpg",
    bio: "Helps students and professionals in career path development and transition planning.",
  },
  {
    id: 6,
    name: "Hina Aslam",
    role: "Training Coordinator",
    category: "Training",
    img: "https://randomuser.me/api/portraits/women/16.jpg",
    bio: "Coordinates teacher training sessions to enhance pedagogical effectiveness.",
  },
  {
    id: 7,
    name: "Imran Javed",
    role: "IT Support Specialist",
    category: "Management",
    img: "https://randomuser.me/api/portraits/men/17.jpg",
    bio: "Manages digital tools and learning management systems for educational projects.",
  },
  {
    id: 8,
    name: "Nida Farooq",
    role: "Academic Mentor",
    category: "Mentoring",
    img: "https://randomuser.me/api/portraits/women/18.jpg",
    bio: "Mentors new teachers and supports them in classroom management and lesson design.",
  },
  {
    id: 9,
    name: "Tariq Bashir",
    role: "Operations Manager",
    category: "Management",
    img: "https://randomuser.me/api/portraits/men/19.jpg",
    bio: "Oversees the operational side of educational services and training sessions.",
  },
  {
    id: 10,
    name: "Zara Noman",
    role: "Psychological Counselor",
    category: "Counseling",
    img: "https://randomuser.me/api/portraits/women/20.jpg",
    bio: "Works on emotional and academic well-being of students and teachers.",
  },
  {
    id: 11,
    name: "Hamza Qureshi",
    role: "Workshop Facilitator",
    category: "Training",
    img: "https://randomuser.me/api/portraits/men/21.jpg",
    bio: "Conducts skill-based workshops for teachers on classroom innovation.",
  },
  {
    id: 12,
    name: "Fatima Zafar",
    role: "Parent Liaison Officer",
    category: "Advisory",
    img: "https://randomuser.me/api/portraits/women/22.jpg",
    bio: "Serves as a communication bridge between school and parents to ensure support.",
  },
  {
    id: 13,
    name: "Shahzad Malik",
    role: "STEM Coach",
    category: "Mentoring",
    img: "https://randomuser.me/api/portraits/men/23.jpg",
    bio: "Encourages students in hands-on STEM activities and competitions.",
  },
  {
    id: 14,
    name: "Maryam Ali",
    role: "Education Researcher",
    category: "Management",
    img: "https://randomuser.me/api/portraits/women/24.jpg",
    bio: "Researches new educational trends and contributes to program development.",
  },
  {
    id: 15,
    name: "Rashid Iqbal",
    role: "Leadership Coach",
    category: "Mentoring",
    img: "https://randomuser.me/api/portraits/men/25.jpg",
    bio: "Helps educators and school heads develop leadership and decision-making skills.",
  },
];

export default TeamData;
